
services:
  # --------------
  # Frontend build
  # --------------
  frontend: 
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    labels:
      - "project=hedgehoglabs-demo"


